# Generated by Django 5.1.6 on 2025-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_watchlist_avg_rating_watchlist_number_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
